#!/usr/local/bin/lua

_G.package.preload['meld'] =
  function(...)
    require('workshop.base')
    local Config = {modules_dir = arg[1], root_module = arg[2]}
    local usage_help =
      [[
Merge all .lua files under given directory into one executable
code block and print it.

Usage

  meld <modules_dir> <root_module_name>

Example

  $ meld test_case/ test > ingots/test.lua

Parameters

  <modules_dir> -- Directory from which we search for .lua files.

  <root_module_name> -- Name of the "main" module which is called
    in generated code block.

-- Martin, 2026-06
]]
    local add_dir_postfix = request('!.concepts.path_name.add_dir_postfix')
    local FilesLister = request('!.concepts.FilesLister.Interface')
    local file_to_str = request('!.convert.file_to_str')
    local add_to_list = request('!.concepts.list.add_item')
    local string_ends_with = request('!.string.ends_with')
    local lua_quote_string = request('!.concepts.lua.quote_string')
    local is_lua_file =
      function(file_name)
        return string_ends_with(file_name, '.lua')
      end
    local get_module_name =
      function(file_name)
        local module_name_capture = '(.*)%.lua$'
        return string.match(file_name, module_name_capture)
      end
    local get_modules
    get_modules =
      function(base_dir_name, module_name_prefix, Result)
        FilesLister:SetBaseDirectory(base_dir_name)
        local Files = FilesLister:GetFiles()
        for _, file_name in ipairs(Files) do
          if not is_lua_file(file_name) then
            goto next
          end
          local module_name = module_name_prefix .. get_module_name(file_name)
          local module_code = file_to_str(base_dir_name .. file_name)
          add_to_list(Result, {module_name, module_code})
          ::next::
        end
        local Directories = FilesLister:GetDirectories()
        for _, subdir_name in ipairs(Directories) do
          get_modules(
            base_dir_name .. subdir_name .. '/',
            module_name_prefix .. subdir_name .. '.',
            Result
          )
        end
      end
    local get_modules =
      function(start_dir)
        local Result = {}
        get_modules(start_dir, '', Result)
        return Result
      end
    local emit =
      function(str)
        io.write(str)
        local newline = '\n'
        if not string_ends_with(str, newline) then
          io.write(newline)
        end
      end
    local add_module_registration =
      function(module_name, module_code)
        local quoted_module_name = lua_quote_string(module_name)
        local module_id = '( module ' .. module_name .. ' )'
        emit('-- ( ' .. module_id)
        emit('_G.package.preload[' .. quoted_module_name .. '] =')
        emit('function(...)')
        emit(module_code)
        emit('end')
        emit('-- ) ' .. module_id)
        emit('')
      end
    local add_module_call =
      function(module_name)
        emit("return require('" .. module_name .. "')")
      end
    local meld =
      function(modules_dir, root_module)
        local Modules = get_modules(modules_dir)
        for _, Rec in ipairs(Modules) do
          local module_name = Rec[1]
          local module_code = Rec[2]
          add_module_registration(module_name, module_code)
        end
        add_module_call(root_module)
      end
    do
      local modules_dir = Config.modules_dir
      local root_module = Config.root_module
      if not modules_dir or not root_module then
        io.write(usage_help)
        return
      end
      modules_dir = add_dir_postfix(modules_dir)
      meld(modules_dir, root_module)
    end
  end
_G.package.preload['workshop.base'] =
  function(...)
    local split_name =
      function(qualified_name)
        local prefix_name_pattern = '^(.+%.)([^%.]+)$'
        local prefix, name = qualified_name:match(prefix_name_pattern)
        if not prefix then
          prefix = ''
          name = qualified_name
          if not name:find('^([^%.]+)$') then
            name = ''
          end
        end
        return prefix, name
      end
    local unite_prefixes =
      function(base_prefix, rel_prefix)
        local init_base_prefix, init_rel_prefix = base_prefix, rel_prefix
        local list_without_tail_pattern = '(.+%.)[^%.]-%.$'
        local list_without_head_pattern = '[^%.]+%.(.+)$'
        while rel_prefix:find('^%^%.') do
          if (base_prefix == '') then
            error(
              ([[Link "%s" is outside of caller's prefix "%s".]]):format(
                init_rel_prefix, init_base_prefix
              )
            )
          end
          base_prefix = base_prefix:match(list_without_tail_pattern) or ''
          rel_prefix = rel_prefix:match(list_without_head_pattern) or ''
        end
        return base_prefix .. rel_prefix
      end
    local Names = {}
    local depth = 1
    local get_caller_prefix =
      function()
        local result = ''
        if Names[depth] then
          result = Names[depth].prefix
        end
        return result
      end
    local get_caller_name =
      function()
        local result = 'anonymous'
        if Names[depth] then
          result = Names[depth].prefix .. Names[depth].name
        end
        return result
      end
    local push =
      function(prefix, name)
        depth = depth + 1
        Names[depth] = {prefix = prefix, name = name}
      end
    local pop =
      function()
        depth = depth - 1
      end
    local Dependencies_Map = {}
    local add_dependency =
      function(src_name, dest_name)
        Dependencies_Map[src_name] = Dependencies_Map[src_name] or {}
        Dependencies_Map[src_name][dest_name] = true
      end
    local base_prefix = split_name((...))
    local get_require_name =
      function(qualified_name)
        local caller_prefix
        local is_absolute_name = (qualified_name:sub(1, 2) == '!.')
        if is_absolute_name then
          qualified_name = qualified_name:sub(3)
          caller_prefix = base_prefix
        else
          caller_prefix = get_caller_prefix()
        end
        local prefix, name = split_name(qualified_name)
        prefix = unite_prefixes(caller_prefix, prefix)
        return prefix .. name, prefix, name
      end
    local request =
      function(qualified_name)
        local src_name = get_caller_name()
        local require_name, prefix, name = get_require_name(qualified_name)
        push(prefix, name)
        local dest_name = get_caller_name()
        add_dependency(src_name, dest_name)
        local Results = table.pack(require(require_name))
        pop()
        return table.unpack(Results)
      end
    local is_first_run = (_G.request == nil)
    if is_first_run then
      _G.request = request
      _G.get_dependencies =
        function()
          return Dependencies_Map
        end
      _G.get_base_prefix =
        function()
          return base_prefix
        end
      _G.get_require_name = get_require_name
      local our_require_name = (...)
      push('', our_require_name)
      request('!.system.install_is_functions')()
      request('!.system.install_assert_functions')()
      _G.new = request('!.table.new')
      pop()
    end
  end
_G.package.preload['workshop.system.install_is_functions'] =
  function(...)
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    local type_is =
      function(type_name)
        return
          function(val)
            return (type(val) == type_name)
          end
      end
    local number_is =
      function(type_name)
        return
          function(val)
            if not is_number(val) then
              return false
            end
            return (math.type(val) == type_name)
          end
      end
    local install_is_functions =
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['is_' .. type_name] = type_is(type_name)
        end
        for _, math_type_name in ipairs(NumberTypeNames) do
          _G['is_' .. math_type_name] = number_is(math_type_name)
        end
      end
    return install_is_functions
  end
_G.package.preload['workshop.system.get_program_output_lines'] =
  function(...)
    local shell_execute = request('!.concepts.shell.execute')
    local lines_from_str = request('!.convert.lines_from_str')
    local get_program_output_lines =
      function(shell_cmd)
        assert_string(shell_cmd)
        local is_ok, ExecResult = shell_execute(shell_cmd)
        return lines_from_str(ExecResult.output)
      end
    return get_program_output_lines
  end
_G.package.preload['workshop.system.install_assert_functions'] =
  function(...)
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    local spawn_assert_func =
      function(type_name)
        local checker = _G['is_' .. type_name]
        assert(checker)
        return
          function(val)
            if not checker(val) then
              local err_msg = string.format('assert_%s(%s)', type_name, tostring(val))
              error(err_msg)
            end
          end
      end
    local install_assert_funcs =
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['assert_' .. type_name] = spawn_assert_func(type_name)
        end
        for _, number_type_name in ipairs(NumberTypeNames) do
          _G['assert_' .. number_type_name] = spawn_assert_func(number_type_name)
        end
      end
    return install_assert_funcs
  end
_G.package.preload['workshop.lua.regexp.magic_chars'] =
  function(...)
    return '^$()[]%.?*+-'
  end
_G.package.preload['workshop.lua.regexp.magic_char_pattern'] =
  function(...)
    local magic_chars = request('magic_chars')
    local magic_char_patttern = '[' .. magic_chars:gsub('.', '%%%0') .. ']'
    return magic_char_patttern
  end
_G.package.preload['workshop.lua.regexp.quote'] =
  function(...)
    local magic_char_pattern = request('magic_char_pattern')
    return
      function(s)
        return s:gsub(magic_char_pattern, '%%%0')
      end
  end
_G.package.preload['workshop.mechs.cmdline.get_cmd_listfiles'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local quote = request('!.concepts.shell.quote')
    local glue_words = request('!.concepts.words.to_string')
    return
      function(dir_name)
        local Command = {'find', quote(normalize(dir_name)), '-maxdepth', '1', '-type', 'f'}
        return glue_words(Command)
      end
  end
_G.package.preload['workshop.mechs.cmdline.get_cmd_execute_with_redirects'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local quote = request('!.concepts.shell.quote')
    local glue_words = request('!.concepts.words.to_string')
    return
      function(orig_command, output_file_name, errors_file_name)
        local Command =
          {
            'sh',
            '-c',
            quote(orig_command),
            '1>' .. quote(normalize(output_file_name)),
            '2>' .. quote(normalize(errors_file_name)),
          }
        return glue_words(Command)
      end
  end
_G.package.preload['workshop.mechs.cmdline.get_cmd_listdirs'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local quote = request('!.concepts.shell.quote')
    local glue_words = request('!.concepts.words.to_string')
    return
      function(dir_name)
        local Command =
          {'find', quote(normalize(dir_name)), '-maxdepth', '1', '-mindepth', '1', '-type', 'd'}
        return glue_words(Command)
      end
  end
_G.package.preload['workshop.table.clone'] =
  function(...)
    local cloned = {}
    local clone
    clone =
      function(node)
        if (type(node) == 'table') then
          if cloned[node] then
            return cloned[node]
          else
            local result = {}
            cloned[node] = result
            for k, v in pairs(node) do
              result[clone(k)] = clone(v)
            end
            setmetatable(result, getmetatable(node))
            return result
          end
        else
          return node
        end
      end
    return
      function(node)
        cloned = {}
        return clone(node)
      end
  end
_G.package.preload['workshop.table.new'] =
  function(...)
    local clone = request('clone')
    local patch = request('patch')
    return
      function(base_obj, overriden_params)
        assert_table(base_obj)
        local result = clone(base_obj)
        if is_table(overriden_params) then
          patch(result, overriden_params)
        end
        return result
      end
  end
_G.package.preload['workshop.table.patch'] =
  function(...)
    local apply_table = request('apply_table')
    local patch =
      function(Result, Additions)
        assert_table(Result)
        if is_nil(Additions) then
          return
        end
        assert_table(Additions)
        local Rules =
          {
            {HasA = true, HasB = true, Action = 'use_b'},
            {HasA = false, HasB = true, Action = 'use_a'},
          }
        apply_table(Result, Additions, Rules)
      end
    return patch
  end
_G.package.preload['workshop.table.apply_table'] =
  function(...)
    local use_a_str = 'use_a'
    local use_b_str = 'use_b'
    local get_action =
      function(has_a, has_b, Rules)
        for _, Rule in ipairs(Rules) do
          local is_same_signature = (Rule.HasA == has_a) and (Rule.HasB == has_b)
          if is_same_signature then
            return Rule.Action
          end
        end
        return use_a_str
      end
    local apply_table
    apply_table =
      function(A, B, Rules)
        local a_type = type(A)
        local b_type = type(B)
        local Keys = {}
        do
          for a_key in pairs(A) do
            Keys[a_key] = true
          end
          for b_key in pairs(B) do
            Keys[b_key] = true
          end
        end
        for key in pairs(Keys) do
          local has_a = not is_nil(A[key])
          local has_b = not is_nil(B[key])
          local a_is_table = has_a and is_table(A[key])
          local b_is_table = has_b and is_table(B[key])
          if a_is_table and b_is_table then
            apply_table(A[key], B[key], Rules)
          else
            local action = get_action(has_a, has_b, Rules)
            if (action == use_a_str) then
            elseif (action == use_b_str) then
              A[key] = B[key]
            end
          end
        end
      end
    local check_rule =
      function(Rule)
        local has_a = is_boolean(Rule.HasA)
        local has_b = is_boolean(Rule.HasB)
        local action = Rule.Action
        local is_known_action = (action == use_a_str) or (action == use_b_str)
        return has_a, has_b, is_known_action
      end
    local apply_table_root =
      function(A, B, Rules)
        assert_table(A)
        assert_table(B)
        assert_table(Rules)
        for index, Rule in ipairs(Rules) do
          local has_a, has_b, is_known_action = check_rule(Rule)
          if not (has_a and has_b and is_known_action) then
            local err_msg = 'Unsupported rule at index ' .. tostring(index)
            error(err_msg, 2)
          end
        end
        apply_table(A, B, Rules)
      end
    return apply_table_root
  end
_G.package.preload['workshop.file_system.directory.get_directories_list'] =
  function(...)
    local get_cmd_listdirs = request('!.mechs.cmdline.get_cmd_listdirs')
    local get_program_output_lines = request('!.system.get_program_output_lines')
    local get_dirs_list =
      function(base_dir)
        local cmd_get_dirs = get_cmd_listdirs(base_dir)
        local Dirs = get_program_output_lines(cmd_get_dirs)
        return Dirs
      end
    return get_dirs_list
  end
_G.package.preload['workshop.file_system.directory.get_files_list'] =
  function(...)
    local get_cmd_listfiles = request('!.mechs.cmdline.get_cmd_listfiles')
    local get_program_output_lines = request('!.system.get_program_output_lines')
    local get_files_list =
      function(base_dir)
        local cmd_get_files = get_cmd_listfiles(base_dir)
        local Result = get_program_output_lines(cmd_get_files)
        return Result
      end
    return get_files_list
  end
_G.package.preload['workshop.file_system.file.open'] =
  function(...)
    local normalize_name = request('!.concepts.path_name.normalize')
    local default_mode = 'rb'
    local open_file =
      function(pathname, mode)
        assert_string(pathname)
        assert(is_nil(mode) or is_string(mode))
        pathname = normalize_name(pathname)
        mode = mode or default_mode
        local file, err_msg = io.open(pathname, mode)
        if not file then
          error(err_msg, 2)
        end
        return file
      end
    return open_file
  end
_G.package.preload['workshop.file_system.file.to_string'] =
  function(...)
    local open_file = request('open')
    local load_file_contents =
      function(pathname)
        local File = open_file(pathname, 'rb')
        local result = File:read('a')
        File:close()
        return result
      end
    return load_file_contents
  end
_G.package.preload['workshop.string.ends_with'] =
  function(...)
    local quote_regexp = request('!.lua.regexp.quote')
    local ends_with =
      function(base_str, postfix_str)
        local postfix_pattern = quote_regexp(postfix_str) .. '$'
        local start_pos = string.find(base_str, postfix_pattern)
        local result = is_number(start_pos)
        return result
      end
    return ends_with
  end
_G.package.preload['workshop.string.remove_prefix'] =
  function(...)
    local quote_regexp = request('!.lua.regexp.quote')
    local remove_prefix =
      function(base_str, prefix_str)
        local prefix_regexp = '^' .. quote_regexp(prefix_str)
        local result = string.gsub(base_str, prefix_regexp, '')
        return result
      end
    return remove_prefix
  end
_G.package.preload['workshop.string.content_attributes'] =
  function(...)
    local has_control_chars =
      function(s)
        return s:find('%c') and true
      end
    local has_backslashes =
      function(s)
        return s:find([[%\]]) and true
      end
    local has_single_quotes =
      function(s)
        return s:find([[%']]) and true
      end
    local has_double_quotes =
      function(s)
        return s:find([[%"]]) and true
      end
    local is_nonascii =
      function(s)
        return s:find('[^%w%s_%p]')
      end
    local has_newlines =
      function(s)
        return s:find('[\n\r]')
      end
    return
      {
        has_control_chars = has_control_chars,
        has_backslashes = has_backslashes,
        has_single_quotes = has_single_quotes,
        has_double_quotes = has_double_quotes,
        is_nonascii = is_nonascii,
        has_newlines = has_newlines,
      }
  end
_G.package.preload['workshop.string.split'] =
  function(...)
    local ends_with = request('!.string.ends_with')
    local quote_regexp = request('!.lua.regexp.quote')
    local add_to_list = request('!.concepts.list.add_item')
    local split_string =
      function(str, delimiter)
        assert_string(str)
        assert_string(delimiter)
        if (delimiter == '') then
          return {str}
        end
        if not ends_with(str, delimiter) then
          str = str .. delimiter
        end
        local Result = {}
        local item_capture = '(.-)' .. quote_regexp(delimiter) .. '()'
        local start_pos
        local end_pos
        local item_str
        start_pos = 1
        while true do
          start_pos, end_pos, item_str = string.find(str, item_capture, start_pos)
          if not start_pos then
            break
          end
          add_to_list(Result, item_str)
          start_pos = end_pos + 1
        end
        return Result
      end
    return split_string
  end
_G.package.preload['workshop.convert.lines_from_str'] =
  function(...)
    local split_string = request('!.string.split')
    local string_to_lines =
      function(str)
        local newline = '\n'
        return split_string(str, newline)
      end
    return string_to_lines
  end
_G.package.preload['workshop.convert.file_to_str'] =
  function(...)
    return request('!.file_system.file.to_string')
  end
_G.package.preload['workshop.concepts.lua.NumberTypeNames'] =
  function(...)
    local NumberTypeNames = {'integer', 'float'}
    return NumberTypeNames
  end
_G.package.preload['workshop.concepts.lua.TypeNames'] =
  function(...)
    local TypeNames =
      {'nil', 'boolean', 'number', 'string', 'function', 'thread', 'userdata', 'table'}
    return TypeNames
  end
_G.package.preload['workshop.concepts.lua.quote_string'] =
  function(...)
    local quote_escaped = request('quote_string.linear')
    local quote_intact = request('quote_string.intact')
    local quote_aggressive = request('quote_string.dump')
    local content_funcs = request('!.string.content_attributes')
    local has_control_chars = content_funcs.has_control_chars
    local has_backslashes = content_funcs.has_backslashes
    local has_single_quotes = content_funcs.has_single_quotes
    local has_double_quotes = content_funcs.has_double_quotes
    local has_newlines = content_funcs.has_newlines
    local binary_entities_lengths =
      {[1] = true, [2] = true, [4] = true, [8] = true, [16] = true}
    return
      function(s)
        assert_string(s)
        local quote_func = quote_escaped
        if binary_entities_lengths[#s] and has_control_chars(s) then
          quote_func = quote_aggressive
        elseif
          has_backslashes(s) or
          has_newlines(s) or
          (has_single_quotes(s) and has_double_quotes(s))
        then
          quote_func = quote_intact
        end
        local result = quote_func(s)
        return result
      end
  end
_G.package.preload['workshop.concepts.lua.quote_string.intact'] =
  function(...)
    local has_newlines = request('!.string.content_attributes').has_newlines
    return
      function(s)
        assert_string(s)
        s = s .. ']'
        local eq_chunk = ''
        local postfix
        while true do
          postfix = ']' .. eq_chunk .. ']'
          if not s:find(postfix, 1, true) then
            break
          end
          eq_chunk = eq_chunk .. '='
        end
        local prefix = '[' .. eq_chunk .. '['
        local first_char = s:sub(1, 1)
        if (first_char == '\x0D') or (first_char == '\x0A') then
          prefix = prefix .. first_char
        end
        if has_newlines(s) then
          prefix = prefix .. '\x0A'
        end
        return prefix .. s .. eq_chunk .. ']'
      end
  end
_G.package.preload['workshop.concepts.lua.quote_string.linear'] =
  function(...)
    local quote_char = request('quote_char')
    local custom_quotes = request('custom_quotes')
    return
      function(s)
        local result = s
        result = result:gsub([[\]], quote_char)
        result = result:gsub('[%c]', quote_char)
        local cnt_q1 = 0
        for i in result:gmatch("'") do
          cnt_q1 = cnt_q1 + 1
        end
        local cnt_q2 = 0
        for i in result:gmatch('"') do
          cnt_q2 = cnt_q2 + 1
        end
        if (cnt_q1 <= cnt_q2) then
          result = "'" .. result:gsub("'", custom_quotes["'"]) .. "'"
        else
          result = '"' .. result:gsub('"', custom_quotes['"']) .. '"'
        end
        return result
      end
  end
_G.package.preload['workshop.concepts.lua.quote_string.dump'] =
  function(...)
    local quote_char = request('quote_char')
    return
      function(s)
        assert_string(s)
        return "'" .. s:gsub('.', quote_char) .. "'"
      end
  end
_G.package.preload['workshop.concepts.lua.quote_string.quote_char'] =
  function(...)
    return
      function(c)
        return ([[\x%02X]]):format(c:byte(1, 1))
      end
  end
_G.package.preload['workshop.concepts.lua.quote_string.custom_quotes'] =
  function(...)
    return
      {
        ['\x07'] = [[\a]],
        ['\x08'] = [[\b]],
        ['\x09'] = [[\t]],
        ['\x0a'] = [[\n]],
        ['\x0b'] = [[\v]],
        ['\x0c'] = [[\f]],
        ['\x0d'] = [[\r]],
        ['"'] = [[\"]],
        ["'"] = [[\']],
        ['\\'] = [[\\]],
      }
  end
_G.package.preload['workshop.concepts.shell.quote'] =
  function(...)
    local list_to_str = request('!.concepts.list.to_string')
    local split_string = request('!.string.split')
    local add_to_list = request('!.concepts.list.add_item')
    local special_chars_regexp
    local starts_with_comment_regexp
    do
      local quote_regexp = request('!.lua.regexp.quote')
      do
        local SpecialChars = request('quote.SpecialChars')
        local special_chars_str = list_to_str(SpecialChars)
        special_chars_regexp = '[' .. quote_regexp(special_chars_str) .. ']'
      end
      do
        local SpaceChars = request('quote.SpaceChars')
        local space_chars_str = list_to_str(SpaceChars)
        local space_chars_regexp = '[' .. quote_regexp(space_chars_str) .. ']'
        local comment_char = '#'
        starts_with_comment_regexp = '^' .. space_chars_regexp .. '+' .. comment_char
      end
    end
    local needs_quoting =
      function(str)
        return
          (str == '') or
          not is_nil(string.find(str, special_chars_regexp)) or
          not is_nil(string.find(str, starts_with_comment_regexp))
      end
    local quote
    quote =
      function(str)
        assert_string(str)
        if not needs_quoting(str) then
          return str
        end
        local single_quote = "'"
        if not string.find(str, single_quote) then
          return single_quote .. str .. single_quote
        end
        str = str .. single_quote
        local RawItems = split_string(str, single_quote)
        local Items = {}
        for _, item in ipairs(RawItems) do
          local quoted_item
          if (item == '') then
            quoted_item = ''
          else
            quoted_item = quote(item)
          end
          add_to_list(Items, quoted_item)
        end
        return list_to_str(Items, [[\]] .. single_quote)
      end
    return quote
  end
_G.package.preload['workshop.concepts.shell.execute'] =
  function(...)
    local file_to_str = request('!.convert.file_to_str')
    local get_execute_command = request('!.mechs.cmdline.get_cmd_execute_with_redirects')
    local execute_shell_command =
      function(command)
        local output_filename = os.tmpname()
        local error_filename = os.tmpname()
        local shell_command = get_execute_command(command, output_filename, error_filename)
        local _, result_type_code, result_code = os.execute(shell_command)
        local Result = {}
        if (result_type_code == 'exit') then
          Result.is_aborted = false
        elseif (result_type_code == 'signal') then
          Result.is_aborted = true
        end
        Result.result_code = result_code
        Result.output = file_to_str(output_filename)
        Result.error = file_to_str(error_filename)
        os.remove(output_filename)
        os.remove(error_filename)
        local is_ok = (Result.result_code == 0)
        return is_ok, Result
      end
    return execute_shell_command
  end
_G.package.preload['workshop.concepts.shell.quote.SpecialChars'] =
  function(...)
    local SpaceChars = request('SpaceChars')
    local add_list = request('!.concepts.list.add_list')
    local SpecialChars =
      {
        '"',
        '$',
        '&',
        "'",
        '(',
        ')',
        '*',
        ';',
        '<',
        '>',
        '[',
        [[\]],
        ']',
        '^',
        '`',
        '{',
        '|',
        '}',
      }
    add_list(SpecialChars, SpaceChars)
    return SpecialChars
  end
_G.package.preload['workshop.concepts.shell.quote.SpaceChars'] =
  function(...)
    local SpaceChars = {'\009', '\010', ' '}
    return SpaceChars
  end
_G.package.preload['workshop.concepts.list.to_string'] =
  function(...)
    local to_string =
      function(List, separator_str)
        assert_table(List)
        separator_str = separator_str or ''
        assert_string(separator_str)
        return table.concat(List, separator_str)
      end
    return to_string
  end
_G.package.preload['workshop.concepts.list.add_item'] =
  function(...)
    local add_item =
      function(OurList, item)
        table.insert(OurList, item)
      end
    return add_item
  end
_G.package.preload['workshop.concepts.list.add_list'] =
  function(...)
    local add_list =
      function(OurList, AnotherList)
        table.move(AnotherList, 1, #AnotherList, #OurList + 1, OurList)
      end
    return add_list
  end
_G.package.preload['workshop.concepts.words.to_string'] =
  function(...)
    local list_to_string = request('!.concepts.list.to_string')
    local to_string =
      function(Words)
        return list_to_string(Words, ' ')
      end
    return to_string
  end
_G.package.preload['workshop.concepts.FilesLister.RemoveBaseDirPrefix'] =
  function(...)
    local remove_prefix = request('!.string.remove_prefix')
    local RemoveBaseDirPrefix =
      function(Me, FileNames)
        local base_dir = Me.BaseDir
        for i = 1, #FileNames do
          FileNames[i] = remove_prefix(FileNames[i], base_dir)
        end
        for i = #FileNames, 1, -1 do
          if (FileNames[i] == '') then
            table.remove(FileNames, i)
          end
        end
      end
    return RemoveBaseDirPrefix
  end
_G.package.preload['workshop.concepts.FilesLister.GetFiles'] =
  function(...)
    local get_files_list = request('!.file_system.directory.get_files_list')
    local GetFilesList =
      function(Me)
        local FileNames = get_files_list(Me.BaseDir)
        Me:RemoveBaseDirPrefix(FileNames)
        return FileNames
      end
    return GetFilesList
  end
_G.package.preload['workshop.concepts.FilesLister.GetBaseDirectory'] =
  function(...)
    local GetBaseDir =
      function(Me)
        return Me.BaseDir
      end
    return GetBaseDir
  end
_G.package.preload['workshop.concepts.FilesLister.SetBaseDirectory'] =
  function(...)
    local add_dir_postfix = request('!.concepts.path_name.add_dir_postfix')
    local normalize_name = request('!.concepts.path_name.normalize')
    local SetBaseDir =
      function(Me, base_dir)
        assert_string(base_dir)
        base_dir = add_dir_postfix(base_dir)
        base_dir = normalize_name(base_dir)
        Me.BaseDir = base_dir
      end
    return SetBaseDir
  end
_G.package.preload['workshop.concepts.FilesLister.GetDirectories'] =
  function(...)
    local get_dirs_list = request('!.file_system.directory.get_directories_list')
    local GetDirectories =
      function(Me)
        local Dirs = get_dirs_list(Me.BaseDir)
        Me:RemoveBaseDirPrefix(Dirs)
        return Dirs
      end
    return GetDirectories
  end
_G.package.preload['workshop.concepts.FilesLister.Interface'] =
  function(...)
    return
      {
        SetBaseDirectory = request('SetBaseDirectory'),
        GetBaseDirectory = request('GetBaseDirectory'),
        GetFiles = request('GetFiles'),
        GetDirectories = request('GetDirectories'),
        BaseDir = './',
        RemoveBaseDirPrefix = request('RemoveBaseDirPrefix'),
      }
  end
_G.package.preload['workshop.concepts.path_name.pathname_to_str'] =
  function(...)
    local list_to_str = request('!.concepts.list.to_string')
    local names_sep = '/'
    local pathname_to_str =
      function(Pathname)
        return list_to_str(Pathname, names_sep)
      end
    return pathname_to_str
  end
_G.package.preload['workshop.concepts.path_name.pathname_from_str'] =
  function(...)
    local split_string = request('!.string.split')
    local sep = '/'
    local empty = ''
    local self_dir = '.'
    local upper_dir = '..'
    local pathname_from_str =
      function(path_name)
        assert_string(path_name)
        assert(path_name ~= '', 'Please pass not empty path_name')
        path_name = path_name .. sep
        local Path = split_string(path_name, sep)
        do
          local index = 2
          local current_item
          while (index <= #Path - 1) do
            current_item = Path[index]
            if (current_item == empty) or (current_item == self_dir) then
              table.remove(Path, index)
            else
              index = index + 1
            end
          end
        end
        setmetatable(
          Path,
          {
            __index =
              function(table, key)
                if (key == 'first_node') then
                  return table[1]
                elseif (key == 'last_node') then
                  return table[#table]
                end
              end,
          }
        )
        if (Path.first_node == self_dir) and (#Path >= 3) then
          table.remove(Path, 1)
        end
        if (Path.last_node == self_dir) and (#Path >= 2) then
          Path[#Path] = ''
        end
        local is_directory =
          (Path.last_node == self_dir) or
          (Path.last_node == upper_dir) or
          (Path.last_node == empty)
        if is_directory and ((Path.last_node ~= empty) or (#Path == 1)) then
          table.insert(Path, '')
        end
        return Path
      end
    return pathname_from_str
  end
_G.package.preload['workshop.concepts.path_name.normalize'] =
  function(...)
    local pathname_from_str = request('pathname_from_str')
    local pathname_to_str = request('pathname_to_str')
    local normalize_name =
      function(path_name)
        return pathname_to_str(pathname_from_str(path_name))
      end
    return normalize_name
  end
_G.package.preload['workshop.concepts.path_name.add_dir_postfix'] =
  function(...)
    local ends_with = request('!.string.ends_with')
    local add_dir_postfix =
      function(str)
        local dir_sep = '/'
        if ends_with(str, dir_sep) then
          return str
        end
        return str .. dir_sep
      end
    return add_dir_postfix
  end
return require('meld')