#!/usr/local/bin/lua

package.preload['meld'] =
  function(...)
    require('workshop.base')
    local get_modules_root
    do
      local FilesLister = request('!.concepts.FilesLister')
      local Result
      local add_separator =
        request('!.concepts.path_name.add_separator')
      local get_modules
      do
        local is_lua_file
        local get_module_name
        do
          local lua_extension = '.lua'
          do
            local string_ends_with = request('!.string.ends_with')
            is_lua_file =
              function(file_name)
                return string_ends_with(file_name, lua_extension)
              end
          end
          do
            local module_name_capture
            do
              local quote_regexp = request('!.lua.regexp.quote')
              module_name_capture =
                '(.*)' .. quote_regexp(lua_extension) .. '$'
            end
            local str_match = string.match
            get_module_name =
              function(file_name)
                return str_match(file_name, module_name_capture)
              end
          end
        end
        local file_to_str = request('!.convert.file_to_str')
        local add_to_list = request('!.concepts.list.add_item')
        local pathname_sep
        do
          local PathEls = request('!.concepts.path_name.Syntels')
          pathname_sep = PathEls.separator
        end
        local module_name_sep = '.'
        get_modules =
          function(base_dir_name, module_name_prefix)
            FilesLister:SetBaseDirectory(base_dir_name)
            local Files = FilesLister:GetFiles()
            for _, file_name in ipairs(Files) do
              if not is_lua_file(file_name) then
                goto next
              end
              local module_name =
                module_name_prefix .. get_module_name(file_name)
              local module_code =
                file_to_str(base_dir_name .. file_name)
              add_to_list(Result, { module_name, module_code })
              ::next::
            end
            local Directories = FilesLister:GetDirectories()
            for _, subdir_name in ipairs(Directories) do
              get_modules(
                base_dir_name .. subdir_name .. pathname_sep,
                module_name_prefix .. subdir_name .. module_name_sep
              )
            end
          end
      end
      get_modules_root =
        function(start_dir)
          FilesLister = FilesLister.create()
          Result = {}
          get_modules(add_separator(start_dir), '')
          return Result
        end
    end
    do
      local modules_dir = arg[1]
      local root_module = arg[2]
      local usage_help =
        [[
Merge all .lua files under given directory into one executable
code block and print it.

Usage

  meld <modules_dir> <root_module_name>

Example

  $ meld test_case/ test > ingots/test.lua

Parameters

  <modules_dir> -- Directory from which we search for .lua files.

  <root_module_name> -- Name of the "main" module which is called
    in generated code block.

-- Martin, 2026-08
]]
      local emit
      do
        local newline
        do
          local AsciiChars = request('!.concepts.Ascii.Chars')
          newline = AsciiChars.newline
        end
        local string_ends_with = request('!.string.ends_with')
        emit =
          function(str)
            io.write(str)
            if not string_ends_with(str, newline) then
              io.write(newline)
            end
          end
      end
      local meld
      do
        local add_module_registration
        local add_module_call
        do
          do
            local lua_quote_string =
              request('!.concepts.lua.quote_string')
            add_module_registration =
              function(module_name, module_code)
                local quoted_module_name = lua_quote_string(module_name)
                local prefix_cmt
                local postfix_cmt
                do
                  local module_id = '( module ' .. module_name .. ' )'
                  prefix_cmt = '-- ( ' .. module_id
                  postfix_cmt = '-- )'
                end
                emit(prefix_cmt)
                emit('package.preload[' .. quoted_module_name .. '] =')
                emit('function(...)')
                emit(module_code)
                emit('end')
                emit(postfix_cmt)
                emit('')
              end
          end
          add_module_call =
            function(module_name)
              emit("return require('" .. module_name .. "')")
            end
        end
        meld =
          function(modules_dir, root_module)
            local Modules = get_modules_root(modules_dir)
            for _, Rec in ipairs(Modules) do
              local module_name = Rec[1]
              local module_code = Rec[2]
              add_module_registration(module_name, module_code)
            end
            add_module_call(root_module)
          end
      end
      if not (modules_dir and root_module) then
        emit(usage_help)
        return
      end
      meld(modules_dir, root_module)
    end
  end
package.preload['workshop.base'] =
  function(...)
    local split_name =
      function(qualified_name)
        local prefix_name_pattern = '^(.+%.)([^%.]+)$'
        local prefix, name =
          string.match(qualified_name, prefix_name_pattern)
        if not prefix then
          prefix = ''
          if string.find(qualified_name, '%.') then
            name = ''
          else
            name = qualified_name
          end
        end
        return prefix, name
      end
    local unite_prefixes =
      function(base_prefix, rel_prefix)
        local uplevel_capture = '(.+%.)[^%.]-%.$'
        while (string.sub(rel_prefix, 1, 2) == '^.') do
          if (base_prefix == '') then
            error("Link is outside of caller's prefix.")
          end
          base_prefix = string.match(base_prefix, uplevel_capture) or ''
          rel_prefix = string.sub(rel_prefix, 3)
        end
        return base_prefix .. rel_prefix
      end
    local Names = {}
    local depth = 1
    local get_caller_prefix =
      function()
        local NameRec = Names[depth]
        if not NameRec then
          return ''
        end
        return NameRec.prefix
      end
    local get_caller_name =
      function()
        local NameRec = Names[depth]
        if not NameRec then
          return 'anonymous'
        end
        return NameRec.prefix .. NameRec.name
      end
    local push =
      function(prefix, name)
        depth = depth + 1
        Names[depth] = { prefix = prefix, name = name }
      end
    local pop =
      function()
        depth = depth - 1
      end
    local Dependencies_Map = {}
    local add_dependency =
      function(src_name, dest_name)
        Dependencies_Map[src_name] = Dependencies_Map[src_name] or {}
        Dependencies_Map[src_name][dest_name] = true
      end
    local base_prefix = split_name((...))
    local get_require_name =
      function(qualified_name)
        local caller_prefix
        local is_absolute_name =
          (string.sub(qualified_name, 1, 2) == '!.')
        if is_absolute_name then
          qualified_name = string.sub(qualified_name, 3)
          caller_prefix = base_prefix
        else
          caller_prefix = get_caller_prefix()
        end
        local prefix, name = split_name(qualified_name)
        prefix = unite_prefixes(caller_prefix, prefix)
        return prefix .. name, prefix, name
      end
    local request =
      function(qualified_name)
        local src_name = get_caller_name()
        local require_name, prefix, name =
          get_require_name(qualified_name)
        push(prefix, name)
        local dest_name = get_caller_name()
        add_dependency(src_name, dest_name)
        local Results = table.pack(require(require_name))
        pop()
        return table.unpack(Results)
      end
    local is_first_run = (_G.request == nil)
    if is_first_run then
      _G.request = request
      _G.get_dependencies =
        function()
          return Dependencies_Map
        end
      _G.get_base_prefix =
        function()
          return base_prefix
        end
      _G.get_require_name = get_require_name
      local our_require_name = (...)
      push('', our_require_name)
      request('!.system.install_is_functions')()
      request('!.system.install_assert_functions')()
      _G.new = request('!.table.new')
      pop()
    end
  end
package.preload['workshop.system.install_is_functions'] =
  function(...)
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    local type_is =
      function(type_name)
        return
          function(val)
            return (type(val) == type_name)
          end
      end
    local number_is =
      function(type_name)
        return
          function(val)
            if not is_number(val) then
              return false
            end
            return (math.type(val) == type_name)
          end
      end
    local install_is_functions =
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['is_' .. type_name] = type_is(type_name)
        end
        for _, math_type_name in ipairs(NumberTypeNames) do
          _G['is_' .. math_type_name] = number_is(math_type_name)
        end
      end
    return install_is_functions
  end
package.preload['workshop.system.get_command_output_lines'] =
  function(...)
    local lines_from_str = request('!.convert.lines_from_str')
    local get_command_output_lines =
      function(Command)
        local is_ok, ExecResult = Command:Execute()
        return lines_from_str(ExecResult.output)
      end
    return get_command_output_lines
  end
package.preload['workshop.system.install_assert_functions'] =
  function(...)
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    local spawn_assert_func =
      function(type_name)
        local checker = _G['is_' .. type_name]
        assert(checker)
        return
          function(val)
            if not checker(val) then
              local err_msg =
                string.format('assert_%s(%s)', type_name, tostring(val))
              error(err_msg)
            end
          end
      end
    local install_assert_funcs =
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['assert_' .. type_name] = spawn_assert_func(type_name)
        end
        for _, number_type_name in ipairs(NumberTypeNames) do
          _G['assert_' .. number_type_name] =
            spawn_assert_func(number_type_name)
        end
      end
    return install_assert_funcs
  end
package.preload['workshop.lua.regexp.magic_chars'] =
  function(...)
    return '^$()[]%.?*+-'
  end
package.preload['workshop.lua.regexp.magic_char_pattern'] =
  function(...)
    local magic_chars = request('magic_chars')
    local magic_char_patttern =
      '[' .. magic_chars:gsub('.', '%%%0') .. ']'
    return magic_char_patttern
  end
package.preload['workshop.lua.regexp.quote'] =
  function(...)
    local magic_char_pattern = request('magic_char_pattern')
    return
      function(s)
        return s:gsub(magic_char_pattern, '%%%0')
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_listfiles'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(dir_name)
        local Command =
          {
            'find',
            { normalize(dir_name), '-maxdepth', '1', '-type', 'f' },
          }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_execute_with_redirects'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local quote = request('!.concepts.shell.quote')
    local glue_words = request('!.concepts.words.to_string')
    return
      function(orig_command, output_file_name, errors_file_name)
        local Command =
          {
            'sh',
            '-c',
            quote(orig_command),
            '1>' .. quote(normalize(output_file_name)),
            '2>' .. quote(normalize(errors_file_name)),
          }
        return glue_words(Command)
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_listdirs'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(dir_name)
        local Command =
          {
            'find',
            {
              normalize(dir_name),
              '-maxdepth',
              '1',
              '-mindepth',
              '1',
              '-type',
              'd',
            },
          }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.number.get_bits'] =
  function(...)
    local assert_bit_offs = request('assert_bit_offs')
    local get_bits =
      function(n, start_offs, end_offs)
        assert_integer(n)
        assert_bit_offs(start_offs)
        assert_bit_offs(end_offs)
        assert(start_offs <= end_offs)
        local mask
        mask = (1 << (end_offs + 1)) - 1
        mask = mask & ~((1 << start_offs) - 1)
        return (n & mask) >> start_offs
      end
    return get_bits
  end
package.preload['workshop.number.assert_byte'] =
  function(...)
    local is_byte = request('is_byte')
    return
      function(v)
        assert(is_byte(v))
      end
  end
package.preload['workshop.number.is_byte'] =
  function(...)
    local get_bits = request('get_bits')
    local is_byte =
      function(value)
        if not is_integer(value) then
          return false
        end
        return (value == get_bits(value, 0, 7))
      end
    return is_byte
  end
package.preload['workshop.number.assert_bit_offs'] =
  function(...)
    return
      function(offs)
        assert_integer(offs)
        assert((offs >= 0) and (offs <= 63))
      end
  end
package.preload['workshop.table.clone'] =
  function(...)
    local cloned = {}
    local clone
    clone =
      function(node)
        if (type(node) == 'table') then
          if cloned[node] then
            return cloned[node]
          else
            local result = {}
            cloned[node] = result
            for k, v in pairs(node) do
              result[clone(k)] = clone(v)
            end
            setmetatable(result, getmetatable(node))
            return result
          end
        else
          return node
        end
      end
    return
      function(node)
        cloned = {}
        return clone(node)
      end
  end
package.preload['workshop.table.new'] =
  function(...)
    local clone = request('clone')
    local patch = request('patch')
    return
      function(base_obj, overriden_params)
        assert_table(base_obj)
        local result = clone(base_obj)
        if is_table(overriden_params) then
          patch(result, overriden_params)
        end
        return result
      end
  end
package.preload['workshop.table.patch'] =
  function(...)
    local apply_table = request('apply_table')
    local Rules = { { has_a = true, has_b = true, action = 'replace' } }
    local patch =
      function(Result, Additions)
        apply_table(Result, Additions, Rules)
      end
    return patch
  end
package.preload['workshop.table.create_instance'] =
  function(...)
    local clone = request('clone')
    local attach_methods = request('attach_methods')
    local create_instance =
      function(Data, Methods)
        assert_table(Data)
        assert_table(Methods)
        local Result
        Result = clone(Data)
        attach_methods(Result, Methods)
        return Result
      end
    return create_instance
  end
package.preload['workshop.table.apply_table'] =
  function(...)
    local keep_str = 'keep'
    local replace_str = 'replace'
    local remove_str = 'remove'
    local get_action =
      function(has_a, has_b, Rules)
        for _, Rule in ipairs(Rules) do
          if (Rule.has_a == has_a) and (Rule.has_b == has_b) then
            return Rule.action
          end
        end
        return keep_str
      end
    local apply_table
    apply_table =
      function(A, B, Rules)
        local Keys = {}
        do
          for a_key in pairs(A) do
            Keys[a_key] = true
          end
          for b_key in pairs(B) do
            Keys[b_key] = true
          end
        end
        for key in pairs(Keys) do
          local a_key = A[key]
          local b_key = B[key]
          if is_table(a_key) and is_table(b_key) then
            apply_table(a_key, b_key, Rules)
          else
            local has_a = not is_nil(a_key)
            local has_b = not is_nil(b_key)
            local action = get_action(has_a, has_b, Rules)
            if (action == keep_str) then
              ;
            elseif (action == replace_str) then
              A[key] = B[key]
            elseif (action == remove_str) then
              A[key] = nil
            end
          end
        end
      end
    local check_rule =
      function(Rule)
        local has_a = is_boolean(Rule.has_a)
        local has_b = is_boolean(Rule.has_b)
        local action = Rule.action
        local is_known_action =
          (action == keep_str) or
          (action == replace_str) or
          (action == remove_str)
        return has_a and has_b and is_known_action
      end
    local apply_table_root =
      function(A, B, Rules)
        assert_table(A)
        assert_table(B)
        assert_table(Rules)
        assert(A ~= B)
        for index, Rule in ipairs(Rules) do
          if not check_rule(Rule) then
            error('Unsupported rule.')
          end
        end
        apply_table(A, B, Rules)
      end
    return apply_table_root
  end
package.preload['workshop.table.attach_methods'] =
  function(...)
    local attach_methods =
      function(Object, Methods)
        assert_table(Object)
        assert_table(Methods)
        local Metatable =
          {
            __index = Methods,
            __newindex =
              function()
                error('Table is locked for additions/removals.')
              end,
          }
        setmetatable(Object, Metatable)
      end
    return attach_methods
  end
package.preload['workshop.file_system.directory.get_directories_list'] =
  function(...)
    local get_cmd_listdirs = request('!.mechs.cmdline.get_cmd_listdirs')
    local get_command_output_lines =
      request('!.system.get_command_output_lines')
    local get_dirs_list =
      function(base_dir)
        return get_command_output_lines(get_cmd_listdirs(base_dir))
      end
    return get_dirs_list
  end
package.preload['workshop.file_system.directory.get_files_list'] =
  function(...)
    local get_cmd_listfiles =
      request('!.mechs.cmdline.get_cmd_listfiles')
    local get_command_output_lines =
      request('!.system.get_command_output_lines')
    local get_files_list =
      function(base_dir)
        return get_command_output_lines(get_cmd_listfiles(base_dir))
      end
    return get_files_list
  end
package.preload['workshop.file_system.file.open'] =
  function(...)
    local normalize_name = request('!.concepts.path_name.normalize')
    local default_mode = 'rb'
    local open_file =
      function(pathname, mode)
        assert_string(pathname)
        assert(is_nil(mode) or is_string(mode))
        pathname = normalize_name(pathname)
        mode = mode or default_mode
        local file, err_msg = io.open(pathname, mode)
        if not file then
          error(err_msg, 2)
        end
        return file
      end
    return open_file
  end
package.preload['workshop.file_system.file.to_string'] =
  function(...)
    local open_file = request('open')
    local load_file_contents =
      function(pathname)
        local File = open_file(pathname, 'rb')
        local result = File:read('a')
        File:close()
        return result
      end
    return load_file_contents
  end
package.preload['workshop.string.ends_with'] =
  function(...)
    local quote_regexp = request('!.lua.regexp.quote')
    local ends_with =
      function(base_str, postfix_str)
        local postfix_pattern = quote_regexp(postfix_str) .. '$'
        local start_pos = string.find(base_str, postfix_pattern)
        local result = is_number(start_pos)
        return result
      end
    return ends_with
  end
package.preload['workshop.string.remove_prefix'] =
  function(...)
    local quote_regexp = request('!.lua.regexp.quote')
    local remove_prefix =
      function(base_str, prefix_str)
        local prefix_regexp = '^' .. quote_regexp(prefix_str)
        local result = string.gsub(base_str, prefix_regexp, '')
        return result
      end
    return remove_prefix
  end
package.preload['workshop.string.split'] =
  function(...)
    local ends_with = request('!.string.ends_with')
    local quote_regexp = request('!.lua.regexp.quote')
    local add_to_list = request('!.concepts.list.add_item')
    local split_string =
      function(str, delimiter)
        assert_string(str)
        assert_string(delimiter)
        if (delimiter == '') then
          return { str }
        end
        if not ends_with(str, delimiter) then
          str = str .. delimiter
        end
        local Result = {}
        local item_capture = '(.-)' .. quote_regexp(delimiter) .. '()'
        local start_pos
        local end_pos
        local item_str
        start_pos = 1
        while true do
          start_pos, end_pos, item_str =
            string.find(str, item_capture, start_pos)
          if not start_pos then
            break
          end
          add_to_list(Result, item_str)
          start_pos = end_pos + 1
        end
        return Result
      end
    return split_string
  end
package.preload['workshop.string.get_chars_count'] =
  function(...)
    local str_sub = string.sub
    local str_byte = string.byte
    local get_chars_count =
      function(str)
        local UsedChars_Map = {}
        for index = 1, #str do
          local char = str_sub(str, index, index)
          local code = str_byte(char)
          if is_nil(UsedChars_Map[code]) then
            UsedChars_Map[code] = 0
          end
          UsedChars_Map[code] = UsedChars_Map[code] + 1
        end
        return UsedChars_Map
      end
    return get_chars_count
  end
package.preload['workshop.convert.lines_from_str'] =
  function(...)
    local split_string
    local newline
    do
      split_string = request('!.string.split')
      local AsciiChars = request('!.concepts.Ascii.Chars')
      newline = AsciiChars.newline
    end
    local string_to_lines =
      function(str)
        return split_string(str, newline)
      end
    return string_to_lines
  end
package.preload['workshop.convert.file_to_str'] =
  function(...)
    return request('!.file_system.file.to_string')
  end
package.preload['workshop.concepts.ShellCommand'] =
  function(...)
    local Interface
    do
      local check_core =
        function(Core)
          assert_table(Core)
          assert(#Core == 2)
          assert_string(Core[1])
          assert_table(Core[2])
          for _, arg in ipairs(Core[2]) do
            assert_string(arg)
          end
        end
      local create
      do
        local DefaultCore = { '', {} }
        local create_instance = request('!.table.create_instance')
        create =
          function(OptCore)
            local Core = OptCore or DefaultCore
            check_core(Core)
            return create_instance(Core, Interface)
          end
      end
      local ToString
      do
        local quote = request('!.concepts.shell.quote')
        local add_to_list = request('!.concepts.list.add_item')
        local glue_words = request('!.concepts.words.to_string')
        ToString =
          function(Me)
            check_core(Me)
            local Words = {}
            add_to_list(Words, quote(Me[1]))
            for _, arg in ipairs(Me[2]) do
              add_to_list(Words, quote(arg))
            end
            return glue_words(Words)
          end
      end
      local Execute
      do
        local execute_shell_command =
          request('!.concepts.shell.execute')
        Execute =
          function(Me)
            check_core(Me)
            return execute_shell_command(Me:ToString())
          end
      end
      Interface =
        { create = create, ToString = ToString, Execute = Execute }
    end
    return Interface
  end
package.preload['workshop.concepts.FilesLister'] =
  function(...)
    local get_base_directory =
      function(Me)
        return Me[1]
      end
    local set_base_directory
    do
      local add_separator =
        request('!.concepts.path_name.add_separator')
      local normalize_name = request('!.concepts.path_name.normalize')
      set_base_directory =
        function(Me, base_dir)
          assert_string(base_dir)
          Me[1] = normalize_name(add_separator(base_dir))
        end
    end
    local get_files
    local get_directories
    do
      local get_clean_pathnames
      do
        local empty = ''
        local remove_prefix = request('!.string.remove_prefix')
        local add_to_list = request('!.concepts.list.add_item')
        get_clean_pathnames =
          function(PathNames, base_dir)
            local Result = {}
            for idx, file_name in ipairs(PathNames) do
              local cleaned_file_name =
                remove_prefix(file_name, base_dir)
              if (cleaned_file_name ~= empty) then
                add_to_list(Result, cleaned_file_name)
              end
            end
            return Result
          end
      end
      do
        local get_files_list =
          request('!.file_system.directory.get_files_list')
        get_files =
          function(Me)
            local base_dir = Me:GetBaseDirectory()
            local FileNames = get_files_list(base_dir)
            FileNames = get_clean_pathnames(FileNames, base_dir)
            return FileNames
          end
      end
      do
        local get_dirs_list =
          request('!.file_system.directory.get_directories_list')
        get_directories =
          function(Me)
            local base_dir = Me:GetBaseDirectory()
            local Dirs = get_dirs_list(base_dir)
            Dirs = get_clean_pathnames(Dirs, base_dir)
            return Dirs
          end
      end
    end
    local Interface
    local create
    do
      local DefaultCore
      do
        local self_dir
        do
          local PathEls = request('!.concepts.path_name.Syntels')
          self_dir = PathEls.self_dir
        end
        DefaultCore = { self_dir }
      end
      local create_instance = request('!.table.create_instance')
      create =
        function()
          return create_instance(DefaultCore, Interface)
        end
    end
    Interface =
      {
        create = create,
        SetBaseDirectory = set_base_directory,
        GetBaseDirectory = get_base_directory,
        GetFiles = get_files,
        GetDirectories = get_directories,
      }
    return Interface
  end
package.preload['workshop.concepts.lua.NumberTypeNames'] =
  function(...)
    local NumberTypeNames = { 'integer', 'float' }
    return NumberTypeNames
  end
package.preload['workshop.concepts.lua.TypeNames'] =
  function(...)
    local TypeNames =
      {
        'nil',
        'boolean',
        'number',
        'string',
        'function',
        'thread',
        'userdata',
        'table',
      }
    return TypeNames
  end
package.preload['workshop.concepts.lua.QuoteChars'] =
  function(...)
    local QuoteChars
    do
      local AsciiCodes = request('!.concepts.Ascii.Codes')
      local AsciiChars = request('!.concepts.Ascii.Chars')
      QuoteChars =
        {
          single_quote_code = AsciiCodes.single_quote,
          double_quote_code = AsciiCodes.double_quote,
          backslash_code = AsciiCodes.backslash,
          single_quote = AsciiChars.single_quote,
          double_quote = AsciiChars.double_quote,
          backslash = AsciiChars.backslash,
        }
    end
    return QuoteChars
  end
package.preload['workshop.concepts.lua.quote_string'] =
  function(...)
    local newline_code
    do
      local AsciiCodes = request('!.concepts.Ascii.Codes')
      newline_code = AsciiCodes.newline
    end
    local BinaryEntitiesLengths_Map =
      {
        [1 << 0] = true,
        [1 << 1] = true,
        [1 << 2] = true,
        [1 << 3] = true,
      }
    local single_quote_code
    local double_quote_code
    local backslash_code
    local single_quote
    local double_quote
    local backslash
    do
      local QuoteChars = request('QuoteChars')
      single_quote_code = QuoteChars.single_quote_code
      double_quote_code = QuoteChars.double_quote_code
      backslash_code = QuoteChars.backslash_code
      single_quote = QuoteChars.single_quote
      double_quote = QuoteChars.double_quote
      backslash = QuoteChars.backslash
    end
    local has_messy_control_chars
    do
      local is_control_code =
        request('!.concepts.Ascii.is_control_code')
      has_messy_control_chars =
        function(UsedChars)
          for code in pairs(UsedChars) do
            if is_control_code(code) and (code ~= newline_code) then
              return true
            end
          end
          return false
        end
    end
    local determine_fixed_quote_char =
      function(UsedChars)
        local num_single_quotes = UsedChars[single_quote_code] or 0
        local num_double_quotes = UsedChars[double_quote_code] or 0
        if (num_single_quotes <= num_double_quotes) then
          return single_quote
        else
          return double_quote
        end
      end
    local get_chars_count = request('!.string.get_chars_count')
    local quote_variable = request('quote_string.intact')
    local quote_char_func = request('quote_string.quote_char')
    local str_gsub = string.gsub
    return
      function(str)
        local UsedChars_Map = get_chars_count(str)
        local str_has_messy_control_chars =
          has_messy_control_chars(UsedChars_Map)
        local str_has_messy_printable_chars =
          UsedChars_Map[newline_code] or
          UsedChars_Map[backslash_code] or
          (
            UsedChars_Map[single_quote_code] and
            UsedChars_Map[double_quote_code]
          )
        local use_variable_quotes =
          str_has_messy_printable_chars and
          not str_has_messy_control_chars
        if use_variable_quotes then
          return quote_variable(str)
        else
          local quote_char = determine_fixed_quote_char(UsedChars_Map)
          local quote_all = false
          local quote_control = false
          if str_has_messy_control_chars then
            if BinaryEntitiesLengths_Map[#str] then
              quote_all = true
            else
              quote_control = true
            end
          end
          if quote_all then
            str = str_gsub(str, '.', quote_char_func)
          else
            str = str_gsub(str, backslash, backslash .. backslash)
            str = str_gsub(str, quote_char, backslash .. quote_char)
            if quote_control then
              str = str_gsub(str, '[%c]', quote_char_func)
            end
          end
          return quote_char .. str .. quote_char
        end
      end
  end
package.preload['workshop.concepts.lua.quote_string.intact'] =
  function(...)
    local opening_bracket
    local closing_bracket
    local filler_char
    local newline_char
    local return_char
    do
      local AsciiChars = request('!.concepts.Ascii.Chars')
      opening_bracket = AsciiChars.opening_bracket
      closing_bracket = AsciiChars.closing_bracket
      filler_char = AsciiChars.equals
      newline_char = AsciiChars.newline
      return_char = AsciiChars.carriage_return
    end
    local str_find = string.find
    local str_sub = string.sub
    return
      function(str)
        str = str .. closing_bracket
        local filler_chunk = ''
        do
          while true do
            local postfix =
              closing_bracket .. filler_chunk .. closing_bracket
            if not str_find(str, postfix) then
              break
            end
            filler_chunk = filler_chunk .. filler_char
          end
        end
        local prefix =
          opening_bracket .. filler_chunk .. opening_bracket
        local first_char = str_sub(str, 1, 1)
        local first_char_is_newline =
          (first_char == newline_char) or (first_char == return_char)
        if first_char_is_newline then
          prefix = prefix .. first_char
        end
        local has_newlines = not is_nil(str_find(str, newline_char))
        if has_newlines and not first_char_is_newline then
          prefix = prefix .. newline_char
        end
        return prefix .. str .. filler_chunk .. closing_bracket
      end
  end
package.preload['workshop.concepts.lua.quote_string.quote_char'] =
  function(...)
    local quote_char_fmt = [[\%03d]]
    local str_byte = string.byte
    local str_format = string.format
    return
      function(char)
        return str_format(quote_char_fmt, str_byte(char))
      end
  end
package.preload['workshop.concepts.shell.quote'] =
  function(...)
    local empty = ''
    local single_quote
    local backslash
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      single_quote = Ascii.single_quote
      backslash = Ascii.backslash
    end
    local list_to_str = request('!.concepts.list.to_string')
    local str_find = string.find
    local needs_quoting
    do
      local special_chars_regexp
      local starts_with_comment_regexp
      do
        local quote_regexp = request('!.lua.regexp.quote')
        do
          local SpecialChars = request('quote.SpecialChars')
          local special_chars_str = list_to_str(SpecialChars)
          special_chars_regexp =
            '[' .. quote_regexp(special_chars_str) .. ']'
        end
        do
          local SpaceChars = request('quote.SpaceChars')
          local space_chars_str = list_to_str(SpaceChars)
          local space_chars_regexp =
            '[' .. quote_regexp(space_chars_str) .. ']'
          local comment_char = '#'
          starts_with_comment_regexp =
            '^' .. space_chars_regexp .. '+' .. comment_char
        end
      end
      needs_quoting =
        function(str)
          return
            (str == empty) or
            not is_nil(str_find(str, special_chars_regexp)) or
            not is_nil(str_find(str, starts_with_comment_regexp))
        end
    end
    local split_string = request('!.string.split')
    local add_to_list = request('!.concepts.list.add_item')
    local quote
    quote =
      function(str)
        assert_string(str)
        if not needs_quoting(str) then
          return str
        end
        if not str_find(str, single_quote) then
          return single_quote .. str .. single_quote
        end
        str = str .. single_quote
        local RawItems = split_string(str, single_quote)
        local Items = {}
        for _, item in ipairs(RawItems) do
          local quoted_item
          if (item == empty) then
            quoted_item = empty
          else
            quoted_item = quote(item)
          end
          add_to_list(Items, quoted_item)
        end
        return list_to_str(Items, backslash .. single_quote)
      end
    return quote
  end
package.preload['workshop.concepts.shell.execute'] =
  function(...)
    local execute_shell_command
    do
      local get_is_aborted
      do
        local normal_exit_str = 'exit'
        local aborted_exit_str = 'signal'
        get_is_aborted =
          function(result_type_code)
            if (result_type_code == normal_exit_str) then
              return false
            elseif (result_type_code == aborted_exit_str) then
              return true
            else
              error('Unknown termination status.')
            end
          end
      end
      do
        local get_execute_command =
          request('!.mechs.cmdline.get_cmd_execute_with_redirects')
        local file_to_str = request('!.convert.file_to_str')
        local os_tmpname = os.tmpname
        local os_execute = os.execute
        local os_remove = os.remove
        execute_shell_command =
          function(command)
            local output_filename = os_tmpname()
            local error_filename = os_tmpname()
            local shell_command =
              get_execute_command(
                command, output_filename, error_filename
              )
            local _, result_type_code, result_code =
              os_execute(shell_command)
            local Result = {}
            Result.is_aborted = get_is_aborted(result_type_code)
            Result.result_code = result_code
            Result.output = file_to_str(output_filename)
            Result.error = file_to_str(error_filename)
            os_remove(output_filename)
            os_remove(error_filename)
            local is_ok = (Result.result_code == 0)
            return is_ok, Result
          end
      end
    end
    return execute_shell_command
  end
package.preload['workshop.concepts.shell.quote.SpecialChars'] =
  function(...)
    local SpecialChars
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      local SpaceChars = request('SpaceChars')
      local add_list = request('!.concepts.list.add_list')
      SpecialChars =
        {
          Ascii.single_quote,
          Ascii.double_quote,
          Ascii.dollar_sign,
          Ascii.ampersand,
          Ascii.asterisk,
          Ascii.semicolon,
          Ascii.backslash,
          Ascii.caret,
          Ascii.backtick,
          Ascii.pipe,
          Ascii.less_than,
          Ascii.greater_than,
          Ascii.opening_paren,
          Ascii.closing_paren,
          Ascii.opening_bracket,
          Ascii.closing_bracket,
          Ascii.opening_brace,
          Ascii.closing_brace,
        }
      add_list(SpecialChars, SpaceChars)
    end
    return SpecialChars
  end
package.preload['workshop.concepts.shell.quote.SpaceChars'] =
  function(...)
    local SpaceChars
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      SpaceChars = { Ascii.tab, Ascii.space, Ascii.newline }
    end
    return SpaceChars
  end
package.preload['workshop.concepts.list.to_string'] =
  function(...)
    local to_string =
      function(List, separator_str)
        assert_table(List)
        separator_str = separator_str or ''
        assert_string(separator_str)
        return table.concat(List, separator_str)
      end
    return to_string
  end
package.preload['workshop.concepts.list.add_item'] =
  function(...)
    local add_item =
      function(OurList, item)
        table.insert(OurList, item)
      end
    return add_item
  end
package.preload['workshop.concepts.list.add_list'] =
  function(...)
    local add_list =
      function(OurList, AnotherList)
        table.move(AnotherList, 1, #AnotherList, #OurList + 1, OurList)
      end
    return add_list
  end
package.preload['workshop.concepts.words.to_string'] =
  function(...)
    local list_to_string = request('!.concepts.list.to_string')
    local to_string =
      function(Words)
        return list_to_string(Words, ' ')
      end
    return to_string
  end
package.preload['workshop.concepts.Ascii.Chars'] =
  function(...)
    local Chars
    do
      local Codes = request('Codes')
      local str_char = string.char
      Chars = {}
      for name, code in pairs(Codes) do
        Chars[name] = str_char(code)
      end
    end
    return Chars
  end
package.preload['workshop.concepts.Ascii.Codes'] =
  function(...)
    local Codes =
      {
        bell = 7,
        backspace = 8,
        tab = 9,
        newline = 10,
        vertical_tab = 11,
        form_feed = 12,
        carriage_return = 13,
        space = 32,
        delete = 127,
        plus = 43,
        minus = 45,
        asterisk = 42,
        slash = 47,
        less_than = 60,
        equals = 61,
        greater_than = 62,
        dot = 46,
        comma = 44,
        colon = 58,
        semicolon = 59,
        single_quote = 39,
        double_quote = 34,
        backtick = 96,
        backslash = 92,
        number_sign = 35,
        question_mark = 63,
        bang = 33,
        percent = 37,
        ampersand = 38,
        dollar_sign = 36,
        at_sign = 64,
        caret = 94,
        underscore = 95,
        pipe = 124,
        tilde = 126,
        opening_paren = 40,
        closing_paren = 41,
        opening_bracket = 91,
        closing_bracket = 93,
        opening_brace = 123,
        closing_brace = 125,
      }
    return Codes
  end
package.preload['workshop.concepts.Ascii.is_control_code'] =
  function(...)
    local assert_byte = request('!.number.assert_byte')
    local is_control_code =
      function(code)
        assert_byte(code)
        return (code <= 31) or (code == 127)
      end
    return is_control_code
  end
package.preload['workshop.concepts.path_name.pathname_to_str'] =
  function(...)
    local Syntels = request('Syntels')
    local list_to_str = request('!.concepts.list.to_string')
    local sep = Syntels.separator
    local pathname_to_str =
      function(Pathname)
        return list_to_str(Pathname, sep)
      end
    return pathname_to_str
  end
package.preload['workshop.concepts.path_name.pathname_from_str'] =
  function(...)
    local Syntels = request('Syntels')
    local split_string = request('!.string.split')
    local check_is_absolute = request('is_absolute')
    local check_is_directory = request('is_directory')
    local add_to_list = request('!.concepts.list.add_item')
    local add_list = request('!.concepts.list.add_list')
    local empty = Syntels.empty
    local self_dir = Syntels.self_dir
    local pathname_from_str =
      function(path_name)
        assert_string(path_name)
        if (path_name == empty) then
          error('Empty pathname.')
        end
        local is_absolute
        local is_directory
        local Names = {}
        do
          local upper_dir = Syntels.upper_dir
          local Segments
          do
            local sep = Syntels.separator
            Segments = split_string(path_name .. sep, sep)
          end
          is_absolute = check_is_absolute(Segments)
          is_directory = check_is_directory(Segments)
          for _, segment in ipairs(Segments) do
            if (segment ~= empty) and (segment ~= self_dir) then
              add_to_list(Names, segment)
            end
          end
        end
        if (#Names == 0) and not is_absolute then
          add_to_list(Names, self_dir)
        end
        do
          local Result = {}
          if is_absolute then
            add_to_list(Result, empty)
          end
          add_list(Result, Names)
          if is_directory then
            add_to_list(Result, empty)
          end
          return Result
        end
      end
    return pathname_from_str
  end
package.preload['workshop.concepts.path_name.normalize'] =
  function(...)
    local pathname_from_str = request('pathname_from_str')
    local pathname_to_str = request('pathname_to_str')
    local normalize_name =
      function(path_name)
        return pathname_to_str(pathname_from_str(path_name))
      end
    return normalize_name
  end
package.preload['workshop.concepts.path_name.is_absolute'] =
  function(...)
    local Syntels = request('Syntels')
    local empty = Syntels.empty
    local is_absolute =
      function(Pathname)
        return (Pathname[1] == empty)
      end
    return is_absolute
  end
package.preload['workshop.concepts.path_name.is_directory'] =
  function(...)
    local Syntels = request('Syntels')
    local empty = Syntels.empty
    local self_dir = Syntels.self_dir
    local upper_dir = Syntels.upper_dir
    local is_directory =
      function(Pathname)
        local last_node = Pathname[#Pathname]
        return
          (last_node == empty) or
          (last_node == self_dir) or
          (last_node == upper_dir)
      end
    return is_directory
  end
package.preload['workshop.concepts.path_name.Syntels'] =
  function(...)
    local Syntels =
      { separator = '/', empty = '', self_dir = '.', upper_dir = '..' }
    return Syntels
  end
package.preload['workshop.concepts.path_name.add_separator'] =
  function(...)
    local Syntels = request('Syntels')
    local ends_with = request('!.string.ends_with')
    local sep = Syntels.separator
    local add_separator =
      function(str)
        if ends_with(str, sep) then
          return str
        end
        return str .. sep
      end
    return add_separator
  end
return require('meld')